name: Create Release and Update DOI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'src/app/layout.tsx'
      - 'scripts/updatePdfPage.js'

jobs:
  check-if-skip:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "Proceeding with workflow"
    outputs:
      should_continue: "true"

  check-and-release:
    needs: check-if-skip
    if: needs.check-if-skip.outputs.should_continue == 'true'
    runs-on: ubuntu-latest
    outputs:
      new_doi: ${{ steps.get_doi.outputs.doi }}
      release_created: ${{ steps.release_status.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get date for release
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Yourself To Science - ${{ steps.date.outputs.date }}
          tag_name: v${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          files: |
            public/yourselftoscience.pdf
            public/sitemap.xml
          body: |
            This release includes:
            - Updated resources list
            - Enhanced citation information
            - Latest content as of ${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release created flag
        run: echo "release_created=true" >> $GITHUB_OUTPUT
        id: release_status
          
      - name: Wait for Zenodo to process
        run: |
          echo "Waiting for Zenodo to process the new release..."
          sleep 180
          
      - name: Get DOI from Zenodo
        id: get_doi
        run: |
          ZENODO_RECORD=$(curl -s "https://zenodo.org/api/records?q=conceptrecid:15109360&sort=mostrecent&size=1")
          VERSION_DOI=$(echo $ZENODO_RECORD | jq -r '.hits.hits[0].metadata.doi // "10.5281/zenodo.placeholder"')
          CONCEPT_DOI=$(echo $ZENODO_RECORD | jq -r '.hits.hits[0].metadata.conceptdoi // "10.5281/zenodo.placeholder"')
          
          # Store both DOIs
          echo "doi=$VERSION_DOI" >> $GITHUB_OUTPUT
          echo "concept_doi=$CONCEPT_DOI" >> $GITHUB_OUTPUT
          echo "Retrieved Version DOI: $VERSION_DOI"
          echo "Retrieved Concept DOI: $CONCEPT_DOI"
          
  update-doi:
    needs: check-and-release
    if: needs.check-and-release.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update layout.tsx with new DOI
        run: |
          DOI="${{ needs.check-and-release.outputs.new_doi }}"
          # Only update if we have a real DOI
          if [[ "$DOI" != "10.5281/zenodo.placeholder" && "$DOI" != "" ]]; then
            sed -i 's|citation_doi": ".*"|citation_doi": "'$DOI'"|g' src/app/layout.tsx
            echo "Updated layout.tsx with DOI: $DOI"
          else
            echo "No valid DOI received, skipping update"
          fi
          
      - name: Update PDF generator with DOI
        run: |
          DOI="${{ needs.check-and-release.outputs.new_doi }}"
          # Only update if we have a real DOI
          if [[ "$DOI" != "10.5281/zenodo.placeholder" && "$DOI" != "" ]]; then
            sed -i 's|doiDiv.textContent = `.*`;|doiDiv.textContent = `'$DOI'`;|g' scripts/updatePdfPage.js
            echo "Updated updatePdfPage.js with DOI: $DOI"
          else
            echo "No valid DOI received, skipping update"
          fi
          
      - name: Commit DOI updates
        if: ${{ needs.check-and-release.outputs.new_doi != '10.5281/zenodo.placeholder' && needs.check-and-release.outputs.new_doi != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[skip ci] Update DOI to ${{ needs.check-and-release.outputs.new_doi }}"
          file_pattern: src/app/layout.tsx scripts/updatePdfPage.js